### ISSUE TITLE
Simple installation

### ISSUE THREAD

**Issue by vduseev** [vduseev/tad#4]
## Business requirement

Make it as easy as possible for all users to install the tool.

## Details

- [ ] Rust users: `cargo install tad`
- [ ] MacOS CLI users: `brew install tad`
- [ ] MacOS UI users: `Tad.app` build
- [ ] Windows CLI users: `winget install tad`
- [ ] Windows UI users: `tad.msi` build
- [ ] Debian users: `apt install tad`
- [ ] Fedora users: `dnf install tad`
